name: "parsl-exploration"
channels:
  - "conda-forge"
  - "nodefaults"
dependencies:
  - python ~=3.12.0
  - parsl-with-kubernetes ~=2024.4
  # TODO: Remove once this build is completed: https://github.com/conda-forge/parsl-feedstock/pull/72
  - python-kubernetes

  # We forked Parsl to get around this issue:
  #     https://github.com/Parsl/parsl/pull/3357
  # TODO: Once the PR above is merged, ensure built for conda-forge and move
  #       parsl back out of the pip section
  - pip:
      - "--editable=git+https://github.com/QGreenland-Net/parsl.git@k8s-use-incluser-config-fallback#egg=parsl"
