name: "parsl-exploration"
channels:
  - "conda-forge"
  - "nodefaults"
dependencies:
  - python ~=3.12.0
  # We want to allow incrementing to 2024.5, but forbid 2014.4.8, which had a
  # dependency specification problem:
  #     https://github.com/conda-forge/parsl-feedstock/pull/72
  - parsl-with-kubernetes ~=2024.4,>=2014.4.15
