---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qgnet
  namespace: qgnet

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qgnet
  namespace: qgnet
rules:
- apiGroups: ["", "networking.k8s.io", "extensions", "apps","autoscaling"]
  #apiGroups: ["", "networking.k8s.io", "extensions", "apps","autoscaling", "rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qgnet
  namespace: qgnet
subjects:
- kind: ServiceAccount
  name: qgnet
  namespace: qgnet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qgnet
